---
services:
  database:
    image: postgres:16
    container_name: voting-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voting-db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "idm"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s 

volumes:
  dbdata:
